# Generated by Django 3.1.4 on 2020-12-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user')),
                ('nickname', models.CharField(default='Joe', max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('picture', models.ImageField(default='default-user.png', upload_to='profiles')),
            ],
        ),
    ]
